name: CI + Release [master]

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
      - 'oclif.manifest.json'

env:
  GIT_USER_NAME: brickblock-bot
  GIT_USER_EMAIL: bot@brickblock.io

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn install with caching
        uses: bahmutov/npm-install@v1
      - run: yarn lint

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn install with caching
        uses: bahmutov/npm-install@v1

      - run: yarn test --coverage

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn install with caching
        uses: bahmutov/npm-install@v1

      - run: ./scripts/end-to-end-tests.sh

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn install with caching
        uses: bahmutov/npm-install@v1
      - run: yarn build

  release:
    needs: [lint, test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # The default GITHUB_TOKEN that's auto-generated by GitHub for CI pipelines
          # does not allow us to push the auto-generated CHANGELOG.md and package.json
          # back to the master branch. Hence, using our brickblock-bot user for this.
          token: ${{ secrets.BRICKBLOCK_BOT_TOKEN }}
          # This is necessary for 'standard-version' to generate the right CHANGELOG
          # See: https://github.com/conventional-changelog/conventional-changelog/issues/622
          fetch-depth: 0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org
          scope: '@strong-config'

      - name: Yarn install with caching
        uses: bahmutov/npm-install@v1

      - name: Configure git for pushing back auto-generated CHANGELOG
        run: |
          git config user.name "${GIT_USER_NAME}"
          git config user.email "${GIT_USER_EMAIL}"
          git config push.followTags true
          git config push.default current

      - run: yarn release
      - run: git push --no-verify
      - name: Post changelog to Slack
        run: npx @brickblock/slack-changelog-notifier --projectName $GITHUB_REPOSITORY
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
